# Generated by Django 4.0.4 on 2022-06-07 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_challenges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='categories/default.jpg', upload_to='categories')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('sets', models.IntegerField()),
                ('repeat', models.IntegerField()),
                ('image', models.ImageField(default='workouts/default.jpg', upload_to='workouts')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.workout_categories')),
            ],
        ),
    ]
